config/routes.rb
Route::Application.routes.draw do
  resources :gallaries

end

app/models/gallary.rb
class Gallary < ActiveRecord::Base
	mount_uploader :image1, ImageUploader
	mount_uploader :image2, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gallaries_controller.rb
class GallariesController < ApplicationController
  before_action :set_gallary, only: [:show, :edit, :update, :destroy]

  # GET /gallaries
  # GET /gallaries.json
  def index
    @gallaries = Gallary.all
  end

  # GET /gallaries/1
  # GET /gallaries/1.json
  def show
  end

  # GET /gallaries/new
  def new
    @gallary = Gallary.new
  end

  # GET /gallaries/1/edit
  def edit
  end

  # POST /gallaries
  # POST /gallaries.json
  def create
    @gallary = Gallary.new(gallary_params)

    respond_to do |format|
      if @gallary.save
        format.html { redirect_to @gallary, notice: 'Gallary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallary }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gallaries/1
  # PATCH/PUT /gallaries/1.json
  def update
    respond_to do |format|
      if @gallary.update(gallary_params)
        format.html { redirect_to @gallary, notice: 'Gallary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gallaries/1
  # DELETE /gallaries/1.json
  def destroy
    @gallary.destroy
    respond_to do |format|
      format.html { redirect_to gallaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallary
      @gallary = Gallary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallary_params
      params.require(:gallary).permit(:name, :image1, :image2, :remote_image1_url, :remote_image2_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallaries_helper.rb
module GallariesHelper
end

app/views/gallaries/_form.html.erb
<%= form_for @gallary, :html => {:multipart => true} do |f| %>
  <% if @gallary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallary.errors.count, "error") %> prohibited this gallary from being saved:</h2>

      <ul>
      <% @gallary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  <div class="field">
    <%= f.label :remote_image1_url %><br>
    <%= f.text_field :remote_image1_url %>
  </div>
  <div class="field">
    <%= f.label :remote_image2_url %><br>
    <%= f.text_field :remote_image2_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallaries/edit.html.erb
<h1>Editing gallary</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallary %> |
<%= link_to 'Back', gallaries_path %>

app/views/gallaries/index.html.erb
<h1>Listing gallaries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image1</th>
      <th>Image2</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gallaries.each do |gallary| %>
      <tr>
        <td><%= gallary.name %></td>
        <td><%= gallary.image1 %></td>
        <td><%= gallary.image2 %></td>
        <td><%= link_to 'Show', gallary %></td>
        <td><%= link_to 'Edit', edit_gallary_path(gallary) %></td>
        <td><%= link_to 'Destroy', gallary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallary', new_gallary_path %>

app/views/gallaries/new.html.erb
<h1>New gallary</h1>

<%= render 'form' %>

<%= link_to 'Back', gallaries_path %>

app/views/gallaries/show.html.erb
<style type="text/css">

a.nowandthen{
	position:relative;
	display: block;
	overflow:hidden;
	cursor: pointer;
	width: 500px; /* set width of image container */
	height: 400px; /* set height of image container */
}

a.nowandthen img{
	position:absolute;
	left:0;
	top:0;
	width: 100%;
	height: 100%;
	-moz-transition: all 0.5s ease; /* enable transition */
	-webkit-transition: all 0.5s ease;
	-o-transition: all 0.5s ease;
	-ms-transition: all 0.5s ease;
	transition: all 0.5s ease;
	z-index: 2;
	clip: rect(0,650px,434px,0); /* clip values should be rect(0,image_width,image_height,0) */
}


a.nowandthen img:nth-of-type(2){ /* hide "after" image beneath "before" so it's initially out of view */
	z-index: 1;
}


	a.nowandthen:hover img:nth-of-type(1){ /* clip "before" image to reveal "after" */
	clip: rect(0,0,434px,0); /* clip values should be rect(0,0,image_height,0) */
	opacity: 0;
	}

a.nowandthen.alt{
	width: 300px; /* set width of image container */
	height: 354px; /* set height of image container */
}

a.nowandthen.alt img{
	clip: rect(0,300px,354px,0); /* clip values should be rect(0,image_width,image_height,0) */
}

a.nowandthen.alt:hover img:nth-of-type(1){
	clip: rect(0,0,354px,0); /* clip values should be rect(0,0,image_height,0) */
}

</style>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallary.name %>
</p>

<strong>Image:</strong>
  <a class="nowandthen">
  	<%= image_tag @gallary.image1_url.to_s %>
  	<%= image_tag @gallary.image2_url.to_s %>
  </a>






<%= link_to 'Edit', edit_gallary_path(@gallary) %> |
<%= link_to 'Back', gallaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Route</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>